### ISSUE TITLE
The captcha is no longer displayed on the contact page after updating prestashop 1.7.7.0

### ISSUE THREAD

**Issue by Stephane1874** [nenes25/eicaptcha#168]
**Prestashop Version**  
1.7.7.0

**Eicaptcha version**  
2.0.6

Hello,

I updated from version 1.7.6.9 to 1.7.7.0 of prestashop and since the captcha of the contact form page no longer wants to be displayed, however, it works well on the account creation form.

Here is the error:  "Uncaught (in promise) Error: reCAPTCHA placeholder element must be an element or id"

![Capture-captcha](https://user-images.githubusercontent.com/46202635/101201073-76f17880-3667-11eb-8788-6bef525b37f3.PNG)

Thanks for your help.

**Comment by Neldor89** [comment]
Same issue here :(

**Comment by rm-info** [comment]
Hi, same issue too. If it helps, there's this error when checking in backend that everything is set up correctly:

Errors

    the module is not registered in hook header

It is the only error and it works fine on the subscription page.
Also I couldn't say if it was working on previous versions of Prestashop, I installed it directly on 1.7.7.0

**Comment by nenes25** [comment]
I can confirm that I'm able to reproduce the issue.

But what's weird in my case it's that if you reload several times the contact page,
Some times it works, sometimes not. 
Totally randomly
![image](https://user-images.githubusercontent.com/7163132/101921031-cfc39280-3bcc-11eb-9260-fe2df561ec32.png)

**Comment by rm-info** [comment]
you're right sometimes it appears.
in my case it does when I force reload (Ctrl+F5) and it doesn't in any other cases.
Also the box is displayed on the right without formatting, whereas on the subscription page, it fits perfectly.

**Comment by rm-info** [comment]
found something. When the captcha appears, there's this in the page source:
<script type="text/javascript" async="" src="https://www.gstatic.com/recaptcha/releases/qc5B-qjP0QEimFYUxcpWJy5B/recaptcha__fr.js" crossorigin="anonymous" integrity="sha384-fTuMfAliJVfYh38oCRhSw4QBfBaXu/Y+0T66sUEM7g3gc2pgyM8jPbchfGYFatiP"></script>

when no captcha, the line misses.

**Comment by Neldor89** [comment]
I think is might be something with the new hooks in PS 1.7.7.0, because in PS 1.7.6.9 worked perfectly.

**Comment by nenes25** [comment]
Hello,
I've fixed the behavior the code is available in the repository.
In my case it fixes the issue in all case.

Could one of you check if i it's the case too ?
I'll build a new release if it's ok
[eicaptcha.zip](https://github.com/nenes25/eicaptcha/files/5688913/eicaptcha.zip)

**Comment by rm-info** [comment]
Hi,

I tried by merging the code of eicaptcha.php and adding config_fr.xml in the module directory. This time the captcha doesn't display at all.
I tried installing the module again by providing the new zip. There's nothing either.
(Also, I emptied the cache everytime)
Maybe I don't do it correctly?

**Comment by Stephane1874** [comment]
Hello,

with this new version i have this error, and the captcha is still not displayed.

Uncaught (in promise) TypeError: container.prop is not a function

![Capture](https://user-images.githubusercontent.com/46202635/102091496-30e2a480-3e1f-11eb-9cf4-d58fae536e0e.PNG)

Thank you very much for the help, have a nice day.

**Comment by rm-info** [comment]
after reading Stephane1874's message, I tried again and it worked once.
Then I got the exact same error as he has

**Comment by nenes25** [comment]
Thanks for the tests , that's weird.

I've well identified the cause of the error.
On the contact form I add with javascript a custom placeholder at the end of the form with the script eicaptcha/17/eicaptcha/views/js/eicaptcha-contact-form.js
Then the captcha is render inside this placeholder.

The initial error was related to the fact that the placeholder is not present when google want to load the captcha.
I don't really know what have been changed on it since it was working like this for years :/

That's why my today  workaround was to add the div directly 
cf. https://github.com/nenes25/eicaptcha/commit/c2dc3c49580ec39374317777a01891ce5dea3482 

Waiting this to be corrected, there is an easy fix.

Simply add the code 
`<div id="captcha-box"></div>` 
directly in the template where you want to display the captcha.

**Comment by nenes25** [comment]
Can you try by applying my last commit ?
replace container.prop("id","captcha-box"); by  container.setAttribute("id","captcha-box");

**Comment by Neldor89** [comment]
YEP! Now works with that commit. I tried several times and all times worked in contact form too. Nice :D

**Comment by Stephane1874** [comment]
Hello,

Thank you very much the captcha came back by adding the `<div id="captcha-box"></div>` directly on the contact form with version 2.0.6 of the module.

![Capturedd](https://user-images.githubusercontent.com/46202635/102128839-ba5d9b00-3e4e-11eb-8722-9f3d99024aff.PNG)

Last question how to properly remove the addition of the block in javascript?

```
$(document).ready(function () {
    $('.form-fields').append('<div id="captcha-box"></div>');
});
```

I tried with the new .zip and the patch below, the captcha appears fine but the validation does not work, I have a blank page when I validate the form.

```
var onloadCallback = function() {
      //Fix captcha box issue in ps 1.7.7
       if ( ! document.getElementById("captcha-box")){
            var container = document.createElement("div");
            container.setAttribute("id","captcha-box");
             document.querySelector(".form-fields").appendChild(container);
         }
grecaptcha.render("captcha-box", {"theme" : "' . $this->themes[Configuration::get('CAPTCHA_THEME')] . '", "sitekey" : "' . Configuration::get('CAPTCHA_PUBLIC_KEY') . '"});
            };
```

Good evening and thanks again for the help.

**Comment by nenes25** [comment]
Hello @Stephane1874 

To remove the add in javascript you can simply copy an empty file eicaptcha/views/js/eicaptcha-contact-form.js in your theme directory so nothing will be done.
I've made some small other improvements

Thanks for your test, i still need to test the module in all prestashop 1.7.x version then i'll create a new 2.0.7
Probably next week.

In my case i have no issue with the last modifications.

Regards,

**Comment by rm-info** [comment]
> 
> 
> Can you try by applying my last commit ?
> replace container.prop("id","captcha-box"); by container.setAttribute("id","captcha-box");

Hello,
I confirm too that this fixes the issue.
I tried to fill the form without the captcha, it refuses to validate and with the captcha it accepts.
So everything seems fine, except the position of the frame in the form: 
![image](https://user-images.githubusercontent.com/49327831/102183075-8a91b000-3ead-11eb-80a8-ce3958fe66e0.png)
Whereas strangely, it worked immediately for the subscription form:
![image](https://user-images.githubusercontent.com/49327831/102183140-a9904200-3ead-11eb-8d79-4d478ae99039.png)
I was kinda amazed to see that.
Would someone be kind enough to explain me how it works?

Thank you very much @nenes25 for your work!

**Comment by nenes25** [comment]
Issue fixed with release 2.0.7
