### ISSUE TITLE
captcha appears on instant checkout page

### ISSUE THREAD

**Issue by ross235** [nenes25/eicaptcha#99]
### Your prestashop version
1.6.1.1
### Eicaptcha Version 
0.4.16
### Do you use a specific theme
No
### Issue description
captcha appears on instant checkout page, customer can proceed to next stage without completing the captcha. Is it possible to remove the captcha from the instant checkout page as I fear this causes confusion as it does not need to be completed anyway it seems? Many thanks.

**Comment by nenes25** [comment]
Hi,
The captcha will be remove from opc in the next relase.
Please see #100 

Regards,

**Comment by gonalo123** [comment]
Hello.

The same problem with version 2.0.4 for prestashop 1.7.5.0.

**Comment by nenes25** [comment]
Hi @gonalo123  could you please open a new issue for v 2.0.4 ?
It's not the same code.
The issue is fixed on ps 1.6.x branch

Regards,

**Comment by ross235** [comment]
Hi @nenes25, I have updated to version 0.4.17 but the captcha still appears on instant checkout page

**Comment by eramirezprotec** [comment]
Solution for version 2.0,4 [here](https://github.com/nenes25/eicaptcha/issues/124#issuecomment-710041812).
